### ISSUE TITLE
content for home page

### ISSUE THREAD

**Issue by grudelsud** [devcon-london/devcon-london.github.io#7]
(really minimal) copy for sections

- welcome (who we are and s#)
- become a member (what does it matter, link to t&c, link to form)
- become a sponsor (probably drop us an email to discuss)
- resources (links to gh, other s#?)

**Comment by acewf** [comment]
Let's create just a text file for each section, and people can contribute with ideas for improving the copy.

**Comment by grudelsud** [comment]
pls refer to new website's repo, here https://github.com/devcon-london/website
