### ISSUE TITLE
make the website serverless / static

### ISSUE THREAD

**Issue by grudelsud** [devcon-london/devcon-london.github.io#9]
we probably don't need heroku to submit a google form, do we?

**Comment by acewf** [comment]
i not sure what are the functionalities we are going to implement, but i think we could start using github pages, put a domain on top, and use https://developers.google.com/apps-script/ to store the data from the forms

**Comment by grudelsud** [comment]
@acewf the only problem with gh-pages is that it doesn't allow https on a custom domain, that's why I was thinking of netlify in #10 
other than that, I totally agree with using some google dev tool and avoid using a proxy as we have at the moment for the form on the website. provided we can make it look nice enough :)

**Comment by marcelkornblum** [comment]
As I think you noted in another ticket @grudelsud Google App Scripts could work for this simple use case (form submission). I've had them work as essentially free JS-like API endpoints for simple functionality in the past...

Would be worth looking at all the site-wide requirements before deciding on an approach though obvs. Though if membership is via GH org, having a directory could be FE only (or in fact we could just link to the GH page...)

**Comment by grudelsud** [comment]
the new (WIP) website uses firebase, here: https://github.com/devcon-london/website
